{% set name = "torchview" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchview-{{ version }}.tar.gz
  sha256: c5898fd03d256333c9827000c1f83e1052fbcfc1066032d86b30d429dd942f7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pytorch >=1.7
    - graphviz
    - python-graphviz

test:
  imports:
    - torchview
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mert-kurttutan/torchview
  summary: Visualize Pytorch Models
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/mert-kurttutan/torchview#documentation

extra:
  recipe-maintainers:
    - mert-kurttutan
