{% set name = "torchview" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchview-{{ version }}.tar.gz
  sha256: 677fb6435999669f922146488492f0d5184d99385f9014a5876f452e9d19f92a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pytorch >=1.7
    - graphviz
    - python-graphviz

test:
  imports:
    - torchview
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mert-kurttutan/torchview
  summary: Visualize Pytorch Models
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/mert-kurttutan/torchview#documentation

extra:
  recipe-maintainers:
    - mert-kurttutan
